version: '3.9'

services:
  postgres:
    image: postgres:16-alpine3.20
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "data_kepegawaian"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jasamarga-api
    container_name: jasamarga-api
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=data_kepegawaian

volumes:
  postgres_data:
    driver: local